// This file is auto-generated by scripts/generate-manifests.js
// Do not edit this file manually.
import './BankController';
import './CallController';
import './ContactController';
import './ConversationController';
import './MailController';
import './MessageController';
import './NoteController';
import './PhotoController';
